Repository EMCECS/ECS-CommunityEdition, pull requests merged in 2018-04, with the labels that each got.

#405 Update terraform configuration to work with new vsphere plugin
  Jenkinsfile
  tests/ansible/templates/deploy.yml.j2
  tests/lab.tf
  tests/output.tf
Labels: testing

#406 document update script
  docs/source/README.txt
  docs/source/update-docs.sh
Labels: documentation

#418 upstream-ecs-3.2.0.0
  patches/3.2.0.0/Dockerfile
  patches/3.2.0.0/build.sh
  patches/libexec/patch_script.sh
  tests/lab.tf
  ui/ansible/roles/common_baseline_install/tasks/main.yml
  ui/ansible/roles/common_deploy/tasks/main.yml
  ui/ansible/roles/common_purge_cleanup/tasks/main.yml
  ui/etc/config.yml
  ui/etc/release.conf
  ui/resources/docker/entrypoint.sh
  ui/setup.py
Labels: Major, administration/maintenance, upstream
