Repository EMCECS/ECS-CommunityEdition, pull requests merged in 2018-06, with the labels that each got.

#434 Forgot to enable bucket creation in the step2 macro
  ui/run.sh
Labels: bug

#436 Enable pushing to DockerHub after production image build
  ui/build_image.sh
  ui/libexec/dockerutils.sh
  ui/libexec/versioning.sh
Labels: administration/maintenance, enhancement

#437 Add convenience util to modify bootstrap.conf from cli
  tools/bootstrap-conf.sh
Labels: enhancement

#438 bump version to 2.8.0r
  ui/etc/config.yml
  ui/etc/release.conf
  ui/setup.py
Labels: administration/maintenance

#441 Update README.md
  README.md
Labels: documentation
